-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/fBax9MPVsVaPq6o
V/ifEpSpLC2OrQLAtmzNnEkooamgCgYIKoZIzj0DAQehRANCAATjORN1vZoI3eDd
0YbYJg5EURINuLcZ5vp5bNZlc9BygyzUwfiNBNFfb1+xeVdwXtKhA9sNtCn7vVrL
5x5ySIBc
-----END PRIVATE KEY-----