name: opencentric_lms
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  path_provider_android: ^2.2.10
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^6.0.0
  badges: ^3.0.2
  better_player_plus: ^1.0.5
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.4.0
  connectivity_plus: ^6.1.1
  country_code_picker: ^3.0.0
  country_pickers: ^3.0.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.2.0
  file_picker: ^8.1.4
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  flutter_downloader: ^1.11.1
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^6.1.4
  flutter_local_notifications: ^17.2.1+1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  fluttertoast: ^8.0.9
  get: ^4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^6.2.1
  http: ^1.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.8.0
  modal_bottom_sheet: ^3.0.0
  open_filex: ^4.3.2
  pagination_view: ^2.0.0
  path: ^1.0.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  phone_number: ^2.1.0
  pin_code_fields: ^8.0.1
  share_plus: null
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  shimmer_animation: ^2.1.0+1
  sign_in_with_apple: ^6.1.1
  smooth_page_indicator: ^1.0.0+2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.3
  video_thumbnail: ^0.5.3
  youtube_player_flutter: 9.0.1
  archive: ^3.3.0
  xml: ^6.5.0
  rxdart: ^0.28.0
  http_server: ^1.0.0
  jwt_decoder: ^2.0.1
  html: ^0.15.4
  flutter_zoom_meeting: ^1.0.2
  dart_jsonwebtoken: ^2.14.0
  paypal_payment: ^1.0.0+4
  flutter_stripe: ^11.2.0
  flutter_dotenv: ^5.0.2
  dio: ^5.7.0
  pay: ^2.0.0
  html_editor_enhanced: ^2.6.0
  flutter_pdfview: ^1.3.4
  pdf: ^3.11.1
  flutter_file_downloader: ^2.0.0
  universal_html: ^2.2.4

dependency_overrides:
  flutter_widget_from_html_core: ^0.15.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo/logo.png'
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - .env
    - assets/images/
    - assets/languages/
    - assets/images/notification/
    - assets/logo/
    - assets/images/intro/
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: AtkinsonHyperlegibleMono
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegibleMono-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/AtkinsonHyperlegibleMono-VariableFont_wght.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: LibreFranklin
      fonts:
        - asset: assets/fonts/LibreFranklin.ttf
          weight: 500
        - asset: assets/fonts/LibreFranklin-Italic.ttf